
Code Provided During Labs for 6370 Statistical Computing

# Introduction to R

```{r examine dataframe}

pacman::p_load(dplyr                          # summarize()
               )

# read data
load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# check structure of dataframe; lists types
str(fevdata)

# break another variable into groups; add as column
fevdata <- mutate(fevdata, age_group = cut(age, breaks = 5))

# calculate mean for each age
fev_mean <- summarize(group_by(fevdata, age), fev = mean(fev))

```

# Visualization of Data in R

```{r scatter ggplot basics}
# some of these commands draw on variables created in data examine chunk

# data source (loaded and manipulated in examine chunk)
# load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# download necessary packages
pacman::p_load(ggplot2)                         # ggplot()

# create ggplot; aesthetic map variables
s <- ggplot(fevdata, aes(x = age, y = fev))
s + geom_point()                                # add points for each datum

# demonstrate geom_jitter
s <- ggplot(fevdata, aes(x = age, y = fev))
s + geom_jitter() 

# add color mapping by smoke variable
s <- ggplot(fevdata, aes(x = age, y = fev, color=smoke))
s + geom_point()

# add color mapping by age variable - those 13+
s <- ggplot(fevdata, aes(x = age, y = fev, color=age < 13))
s + geom_point()

# add group mapping by smoke variable
p <- ggplot(fevdata, aes(x = age, y = fev, group = smoke))
p + geom_point() + stat_smooth(aes(color = smoke))  # map color for only smooth component

# specify border color and fill
ggplot(fevdata, aes(x = age, y = fev)) +
  geom_point(color = "black",                   # needs to be defined in geom_point()
             fill = "white", 
             shape = 21, 
             size = 4, 
             stroke = 1)

# plot mean across each age
s <- ggplot(fevdata, aes(x = age, y = fev))     # basic ggplot
s + geom_point() + geom_line(data = fev_mean)   # add line across averages

# option to fix coordinate plane with 1:1 aspect ratio (supposedly)
s + geom_point() + coord_fixed()
```

```{r facet_grid}
# some of these commands may draw on variables created in data examine chunk

# data source (loaded and manipulated in examine chunk)
# load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# download necessary packages
pacman::p_load(dplyr,                           
               ggplot2)                             # ggplot()

# grid with specified rows and columns
p <- ggplot(fevdata, aes(x = height, y = fev)) + 
  facet_grid(rows = vars(sex), cols = vars(age_group))
p + geom_point(aes(color = smoke))

# grid with specified rows only
p <- ggplot(fevdata, aes(x = height, y = fev)) + 
  facet_grid(rows = vars(sex))
p + geom_point(aes(color = smoke))
```


```{r boxplot ggplot basics}
# some of these commands may draw on variables created in data examine chunk

# data source (loaded and manipulated in examine chunk)
# load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# download necessary packages
pacman::p_load(dplyr,                           
               ggplot2)                             # ggplot()

# create boxplot by age
p <- ggplot(fevdata, aes(x = age, y = fev))
p + geom_boxplot(mapping = aes(x = as.factor(age))) # consider age categorical
p + geom_boxplot(mapping = aes(x = as.factor(age_group))) # consider age group

# split and color by smoker status
p + geom_boxplot(mapping = aes(x = as.factor(age_group), fill = smoke))

# option for horizontal box plots
ggplot(fevdata) + 
  geom_boxplot(mapping = aes(x = sex, y = fev)) +
  coord_flip()
```

```{r geom_bar/col plots}
# some of these commands may draw on variables created in data examine chunk

# data source (loaded and manipulated in examine chunk)
# load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# download necessary packages
pacman::p_load(dplyr,                           
               ggplot2)                             # ggplot()

# geom_bar plot requires group = 1 to consider as a whole rather than by cut
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, group = 1))
```

```{r pie chart}

# download necessary packages
pacman::p_load(dplyr,                           
               ggplot2)                             # ggplot()

# pie chart of diamond cut
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(y = 1, fill = cut)) +
  coord_polar()

# equivalent pie chart
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = 1, fill = cut)) +
  coord_polar(theta = "y")
```

# Smoothing and Density Estimation

```{r manual smoothing}

# data source (loaded and manipulated in examine chunk)
# load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# use linear regression
linear_model <- lm(fev ~ age, data=fevdata)              # fit linear model
target_values <- data.frame(
  age = seq(from = min(fevdata$age), 
            to = max(fevdata$age), 
            length.out = 100)
)                                                        # create x values
predictions <- mutate(target_values, 
                      fev = predict(linear_model, 
                                    newdata = target_values)
                      )                                  # find y_hats
p <- ggplot(data = fevdata, mapping = aes(x = age, y = fev))
p + 
  geom_point() +                                         # scatter plot
  geom_line(data = predictions, color = "red")           # linear overlay

# locally-weighted smoothers
polynomial_model <- loess(fev ~ age,
                          data = fevdata,
                          degree = 2,                     # ??
                          span = .75)                     # window to consider
predictions <- mutate(target_values,
                      fev = predict(polynomial_model,     # new predictions
                                    newdata = target_values)
                      )
p +
  geom_point() +
  geom_line(data = predictions, color = "red")

# map color to line with legend
p +
  geom_point() + 
  geom_line(data = predictions, mapping = aes(color = "Original Line")) + 
  geom_line(data = 2+predictions, mapping = aes(color = "Demonstrate"))

```

```{r geom_smooth()}

# data source (loaded and manipulated in examine chunk)
# load(url("https://www.stat.osu.edu/~vqv/6730/data/fev.RData"))

# basic plot
p <- ggplot(data = fevdata, mapping = aes(x = age, y = fev))

# show geom_smooth
p + 
  geom_point() + 
  geom_smooth()

# linear geom_smooth
p + 
  geom_point() + 
  geom_smooth(method = lm)

# IMPORTANT
# Confidence Intervals generated by GGPlot are NOT valid if the model is not true
# turn off confidence bounds
p + 
  geom_point() + 
  geom_smooth(se = FALSE)

# polynomial geom_smooth
p + 
  geom_point() + 
  geom_smooth(method = loess,
              method.args = list(degree = 2, span = .75))

# specify desired model
p + 
  geom_point() + 
  geom_smooth(method = lm,
              formula = y~x+I(x^2), se = FALSE)
p + 
  geom_point() + 
  geom_smooth(method = lm, formula = y~poly(x, degree = 3), se = FALSE)

# view by smoker status
p + 
  geom_point(aes(color = smoke)) +                     # map point color to smoke
  geom_smooth(aes(color = smoke)) +                    # map lines to smoke
  facet_grid(rows = vars(smoke))                       # separate plots

```

# Generating Random Variables

```{r Simulation Basics}

# uniform distribution
x_unif <- runif(400, min = -3, max = 5)
hist(x_unif,
     col = "cadetblue2")

# normal distribution
x_norm <- rnorm(n = 400, mean = 120, sd = 4)

# exponential distribution
x_exp <- rexp(400, rate = 1)

# probability density/mass function
dnorm()

# cumulative distribution function
pnorm()
```

```{r Sampling}

# sample from numbers 1 thorugh 5
x_s <- sample(1:5, size = 10, replace = TRUE)
print(x_s)

# equivalent to
x_s <- sample(5, size = 10, replace = TRUE)
print(x_s)

```

# Monte Carlo Simulation

```{r monte carlo simulation}
# load information
source(url("https://www.stat.osu.edu/~vqv/6730/data/lab_05.R"))
load(url("https://www.stat.osu.edu/~vqv/6730/data/lab_05.RData"))
out <- ztp.mle(before_sales)
lambda_historical <- out$lambda

# simulation
sample_ts <- replicate(1000, {
  # sample 1000 from truncated poisson
  x <-
    rtruncpois(10,
               lambda = 1,
               truncation = 0)
  
  # take average (in this example, desired T definition was provided)
  t_realization <- mean(x)
})

# assign g: 1 if included in proportion, 0 if not
g <- ifelse(sample_ts >= 2, 1, 0)

# average of g is proportion included
mean(g)

# /////////////////////////////////////////////////////////////////////////////
# Homework 4 Extended (from Lab 4) Example

library(tidyverse)

source(url("https://www.stat.osu.edu/~vqv/6730/data/lab_05.R"))
load(url("https://www.stat.osu.edu/~vqv/6730/data/lab_05.RData"))

# truncated poisson pdf
dtruncpois <- function(x, lambda, truncation) {
  ifelse(x > truncation, 
    dpois(x, lambda) / ppois(truncation, lambda, lower.tail = FALSE),
    0
  )
}

# function to randomly generate numbers from dtruncpois
rtruncpois <-
  function(n,
           lambda,
           truncation,
           proposal_mean = max(lambda, truncation)) {
    
    M <-
      (dpois(truncation + 1, lambda) / dpois(truncation + 1, proposal_mean)) /
      ppois(truncation, lambda, lower.tail = FALSE)
    
    replicate(n, {
      accept <- FALSE
      while (!accept) {
        
        # Generate proposal
        x <- rpois(1, proposal_mean)
        
        # Generate uniform on [0, M * g(x)]; accept if the uniform falls under f(x)
        u <- runif(1,
                   min = 0,
                   max = M * dpois(x, proposal_mean))
        accept <- u <= dtruncpois(x, lambda, truncation)
      }
      x # ensure the inner block returns x
    })
  }

# find the mean of ten random numbers from rtruncpois
x <- rtruncpois(10, lambda = 1, truncation = 0)
t_realization <- mean(x)

# repeat for 1e4 simulations
n_sim <- 1e4
t_realization <- replicate(n_sim, 
                           mean(rtruncpois(10, lambda = 1, truncation = 0)))

# proportion over 2 using monte carlo
(p_2 <- mean(t_realization >= 2))

```

# The Bootstrap

```{r estimate}
# /////////////////////////////////////////////////////////////////////////////
# Background Info
# /////////////////////////////////////////////////////////////////////////////

# read data
fish <- read_table('https://www.stat.osu.edu/~vqv/6730/data/fish.txt')

# beverton holt function
bh <- function(S, beta1, beta2) {
  R <- 1 / (beta1 + (beta2/S))
}

# fit linear model on 1/R and 1/S
bh_lm <- lm(I(1/R) ~ I(1/S), data = fish)

# retrieve coefficients
beta1 <- coef(bh_lm)[1]
beta2 <- coef(bh_lm)[2]

# stable population size
N_stable <- (1-beta2)/ beta1

# /////////////////////////////////////////////////////////////////////////////
# Bootstrap Begins Here
# /////////////////////////////////////////////////////////////////////////////

# function to find N for stable population
N_hat <- function(df) {
  
  # fit linear model
  bh_lm <- lm(I(1/R) ~ I(1/S), data = df)
  
  # coefficients for b1 and b2
  beta1 <- coef(bh_lm)[1]
  beta2 <- coef(bh_lm)[2]

  estimate <- (1-beta2)/ beta1
  return(estimate)
}

# bootstrap fish to find sampling distribution
boot_fish <- replicate(1000, {
  
  # take a sample with replacement of size = fish
  x <- slice_sample(fish, n = nrow(fish), replace = TRUE)
  
  # perform n_hat on each sampled row
  summarize(x,
            n_hat = N_hat(x))
}, simplify = FALSE)

# combines list of dataframes into one dataframe
boot_fish <- bind_rows(boot_fish)

# mean
mean(boot_fish$n_hat)

# standard error
sd(boot_fish$n_hat)
```

```{r bootstrap confidence interval}
# set confidence level
alpha <- .05

# set number of bootstrap samples
B <- 1000

# bootstrap for CI
boot_pivot <- replicate(B, {
  df_boot <- slice_sample(fish, n = nrow(fish), replace = TRUE)
  N_hat(df_boot) - N_hat(fish)
})

# Use setNames to replace the names that quantile() gives its output
q <- setNames(quantile(boot_pivot, c(1 - alpha/2, alpha/2)), NULL)
confidence_interval <- N_hat(fish) - q

# print confidence interval
confidence_interval
```

# Functional Programming
```{r purrr}
# load packages
pacman::p_load(dplyr,
               ggplot2,
               nycflights13,
               read4,
               purrr)

# find mean of every column of mtcars
map_dbl(mtcars, mean)

# find type of each column in nycflights
map_chr(flights, typeof)

# find number of unique values in each column
map_int(iris, function(x) length(unique(x)))

# generate four samples of size ten with specified means
map(c(-10, 0, 10, 100), rnorm, n = 10)

# read data
fish <- read_table('https://www.stat.osu.edu/~vqv/6730/data/fish.txt')

# function for population size
N_hat <- function(df){
  fitted_model <- lm(I(1/R) ~ I(1/S), data = df)
  beta <- unname(coef(fitted_model))
  (1 - beta[2]) / beta[1]
}

# number of bootstrap replicates
n_bootstrap_replicates <- 1e3

# create bootstrap samples
fish_boot <- map(1:n_bootstrap_replicates,
                 function(x) slice_sample(fish, 
                                          n = nrow(fish), 
                                          replace = TRUE)
                 )

# evaluate n_hat on samples
N_hat_boot <- map_dbl(fish_boot, N_hat)

# find standard error of result
(N_hat_se <- sd(N_hat_boot))

# store linear models fit to each bootstrap
linear_models <- map(fish_boot, function(x) lm(I(1/R) ~ I(1/S), data = x))

# store coefficients of linear models
coef_boot <- map(linear_models, coef)

# function to estimate R from S
bh_curve <- function(beta, S) {
  tibble(
    S = S,
    R = 1 / (beta[1] + (beta[2] / S))
  )
}

# create curve using betas from coef_boot
bh_boot <- map(coef_boot, bh_curve, S = seq(50,500,by=1))

# bind rows and store list # in id column
bh_boot_df <- bind_rows(bh_boot, .id = "bootstrap_replicate")

# plot the curves
ggplot(fish, mapping = aes(x = S, y = R)) +
  geom_point() +
  geom_line(
    data = bh_boot_df,
    mapping = aes(group = bootstrap_replicate),
    alpha = 1 / 20
  )
```

# Permutation Methods

# Cross-Validation


